### PR TITLE
fix: align vitest peer dependency

### PR DESCRIPTION
**Pull request by angelfraga**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [x] create-analog
- [ ] router
- [ ] platform
- [ ] content
- [ ] nx-plugin
- [ ] trpc

## What is the current behavior?

Hi, it seems that following the guides and creating the analog app did stuck due dependencies after running npm install.
I think it can be solved by just adding `"vitest": "^1.3.1"`  .

node v20.10.0
npm 10.2.3
Windows 11

I did clean up the cache before

`npm cache clean` 
`npm cache verify`

Cache verified and compressed (~\AppData\Local\npm-cache\_cacache)
Content verified: 0 (0 bytes)
Index entries: 0
Finished in 0.007s

Then

`npm create analog@latest`

(I took angular 17 from the options)
```npm i 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: analog-project@0.0.0
npm ERR! Found: vitest@1.2.2
npm ERR! node_modules/vitest
npm ERR!   dev vitest@"~1.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vitest@"^1.3.1" from @nx/vite@18.0.5
npm ERR! node_modules/@nx/vite
npm ERR!   dev @nx/vite@"~18.0.0" from the root project
npm ERR!   peer @nx/vite@"^16.0.0 || ^17.0.0 || ^18.0.0" from @analogjs/platform@0.2.39
npm ERR!   node_modules/@analogjs/platform
npm ERR!     dev @analogjs/platform@"^0.2.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Closes #

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by angelfraga** [comment]
Hi, it seems that following the guides and creating the analog app did stuck due dependencies after running npm install.
I think it can be solved by just adding `"vitest": "^1.3.1"`  .

node v20.10.0
npm 10.2.3
Windows 11

I did clean up the cache before

`npm cache clean` 
`npm cache verify`

Cache verified and compressed (~\AppData\Local\npm-cache\_cacache)
Content verified: 0 (0 bytes)
Index entries: 0
Finished in 0.007s


Then

`npm create analog@latest`

(I took angular 17 from the options)
```npm i 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: analog-project@0.0.0
npm ERR! Found: vitest@1.2.2
npm ERR! node_modules/vitest
npm ERR!   dev vitest@"~1.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vitest@"^1.3.1" from @nx/vite@18.0.5
npm ERR! node_modules/@nx/vite
npm ERR!   dev @nx/vite@"~18.0.0" from the root project
npm ERR!   peer @nx/vite@"^16.0.0 || ^17.0.0 || ^18.0.0" from @analogjs/platform@0.2.39
npm ERR!   node_modules/@analogjs/platform
npm ERR!     dev @analogjs/platform@"^0.2.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.```

**Comment by brandonroberts** [comment]
Thanks @angelfraga. We need to validate that Vitest 1.3.x works in this repo also by updating the Vitest version in the root `package.json` and running `pnpm i` and `pnpm test` and submit those changes also. I had some issues with Vitest 1.3.x, which is why we're currently pinned to 1.2.x.

**Comment by angelfraga** [comment]
@brandonroberts alright, I am going to check it afterwork.

**Comment by angelfraga** [comment]
@brandonroberts after adding the changes in the root package.json, test does pass in WSL but not in windows (with and without my changes)

Test affected are:

```
 - nx run vite-plugin-angular:test
 - nx run vite-plugin-nitro:test
```

I think these issues I am facing in windows are related to nitropack in windows mentioned here

https://github.com/analogjs/analog/issues/688

So I guess these test would be fixed along the nitropack fix. 

Btw I was able to reproduce the npm install error in WSL 

```
node 20.11.1
npm 10.2.4
```

I think it would be great to get rid of the npm install error since affect both Windows & WSL

Otherwise a workaround is just installing with `--force`  flag, but in that case I would be happy to add some known issues docs to the docs.

**Comment by brandonroberts** [comment]
@angelfraga thanks. The Windows outside of WSL is a known issue people are still trying to help debug, but this will fix the install issues.

Will you update this file also? https://github.com/analogjs/analog/blob/main/packages/create-analog/template-blog/package.json

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Thanks! @allcontributors add @angelfraga for infra

**Pull request merged**
