### PR TITLE
fix(content): fix deprecation warnings for marked package

### LINKED ISSUE #482: Feature: Fix deprecation warnings for marked package
### Which scope/s are relevant/related to the feature request?

content

### Information

When serving the application and prerendering routes, a console warning is shown for the marked package

```
marked(): highlight and langPrefix parameters are deprecated since version 5.0.0, should not be used and will be removed in the future. Instead use https://www.npmjs.com/package/marked-highlight.
marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
```

This would update the `packages/content/src/lib/markdown-content-renderer.service.ts` to use the new configuration and remove the deprecation warning.

### Describe any alternatives/workarounds you're currently using

_No response_

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by luishcastroc**
Fixed by adding the new extensions as well added a test

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [ ] create-analog
- [ ] router
- [ ] platform
- [x] content
- [ ] nx-plugin
- [ ] trpc

## What is the current behavior?

When serving the application and prerendering routes, a console warning is shown for the marked package

```
marked(): highlight and langPrefix parameters are deprecated since version 5.0.0, should not be used and will be removed in the future. Instead use https://www.npmjs.com/package/marked-highlight.
marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
```

Closes #482 

## What is the new behavior?

After the fix no warning should appear.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by luishcastroc** [comment]
#487 Hope this works 🥇

**Comment by luishcastroc** [comment]
> Thanks @luishcastroc! Things aren't rendering correctly now comparing the deploy preview against the current version
> 
> https://deploy-preview-487--analog-blog.netlify.app/blog/2022-12-31-my-second-post https://analog-blog.netlify.app/blog/2022-12-31-my-second-post
> 
> If you go to https://deploy-preview-487--analog-blog.netlify.app/blog and click "My Second Post", it doesn't show the code snippet. If you refresh the page, it shows correctly.
> 
> The e2e test failure is unrelated so don't worry about that for now.

Thanks i really didn't know how to test it properly so i gave it a shot but with that i can now tell for sure, let me give it a look

**Comment by luishcastroc** [comment]
@brandonroberts i think it should be fixed now however e2e seems to be still failing.

**Comment by brandonroberts** [comment]
@luishcastroc works as expected! 

Question: What do you think about turning the `Marked` object into an `Injectable` service? Like a `marked.service.ts` class that's provided/injected into the `MarkdownContentRenderService` internally?

It would still behave like a singleton.

**Comment by luishcastroc** [comment]
> @luishcastroc works as expected!
> 
> Question: What do you think about turning the `Marked` object into an `Injectable` service? Like a `marked.service.ts` class that's provided/injected into the `MarkdownContentRenderService` internally?
> 
> It would still behave like a singleton.

i was thinking on this however since all the logic was inside the service i just complemented with the new approach, i think since this is an angular ecosystem it definitely makes sense so let me do the proper changes.

thanks for the feedback.

**Comment by luishcastroc** [comment]
> @luishcastroc works as expected!
> 
> Question: What do you think about turning the `Marked` object into an `Injectable` service? Like a `marked.service.ts` class that's provided/injected into the `MarkdownContentRenderService` internally?
> 
> It would still behave like a singleton.

@brandonroberts i sent a commit with the markedService injected in root but i wanted to know in your experience if that would be the best approach (seems to be straight forward after that). another one i tried was this.

```ts
export function withMarkdownRenderer(): Provider {
  return {
    provide: ContentRenderer,
    useClass: MarkdownContentRendererService,
    deps: [MarkedSetupService],
  };
}

export function provideContent(...features: Provider[]) {
  return [...features, MarkedSetupService];
}
```
not sure if that would be the best

**Comment by brandonroberts** [comment]
@luishcastroc I think it should follow the same pattern as the provider and not use `providedIn: 'root'`. That way if you want to lazy load the provideContent you can

**Review by brandonroberts — APPROVED** [review]
LGTM

**Comment by brandonroberts** [comment]
Thanks for pushing through @luishcastroc! We'll need to add a migration for the new dependencies but that can be done separately.

**Comment by brandonroberts** [comment]
@allcontributors add @luishcastroc for code

**Comment by luishcastroc** [comment]
> Thanks for pushing through @luishcastroc! We'll need to add a migration for the new dependencies but that can be done separately.

let me read a little bit about how to do this and I'll take a look

**Pull request merged**
