### PR TITLE
feat(vite-plugin-angular): introduce support for Angular v19 HMR/live reload

### LINKED ISSUE #1524: Enable HMR/Live Reload behavior with Angular v19
### Which scope/s are relevant/related to the feature request?

vite-plugin-angular

### Information

Angular v19 introduces native HMR/Live Reload functionality with Vite's dev server. There should be an option to enable this through the Analog plugin.

### Describe any alternatives/workarounds you're currently using

Normal behavior with page reloads on changes.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by brandonroberts**
## PR Checklist

Closes #1524

## What is the new behavior?

When using the `liveReload` option in the `analog` plugin with Angular v19, the new HMR code generated by the compiler is handled by the vite plugin, enabling HMR updates without full page reloads.

- Inline styles and templates are supported
- External styles and templates are supported
- Page reloads occur when classes are changed (logic copied from Angular compilation)

```ts
/// <reference types="vitest" />

import { defineConfig } from 'vite';
import analog from '@analogjs/platform';

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => ({
  // ..other config
  plugins: [analog({ liveReload: true })],
}));
```

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Links
https://vite.dev/guide/api-plugin.html#handlehotupdate
https://bjornlu.com/blog/hot-module-replacement-is-easy#importmetahotaccept

### CODE REVIEW

**Comment by sawa-ko** [comment]
Finally someone did what angular has never been able to, HMR without reloading the page completely.

I still don't understand how the community has been asking for it for years but they can't do it...

**Comment by brandonroberts** [comment]
> Finally someone did what angular has never been able to, HMR without reloading the page completely.
> 
> I still don't understand how the community has been asking for it for years but they can't do it...

@sawa-ko that's incorrect. It's enabled in Angular v19 already through the Angular CLI and will be the default for new apps in 19.1. We integrated the HMR functionality into Analog.

**Comment by sawa-ko** [comment]
Hum, but the angular HMR keeps reloading the entire page when a component changes, right?

**Comment by sawa-ko** [comment]
Hum, but the angular HMR keeps reloading the entire page when a component changes, right?

And no, I don't mean the CSS HMR.

**Comment by brandonroberts** [comment]
@sawa-ko By default yes, HMR has to be enabled manually using an environment variable.

```sh
NG_HMR_TEMPLATES=1 ng serve
``` 

This will be enabled by default for newly created Angular apps in Angular v19.1 which hasn't been released yet. You can also enable it with the `liveReload: true` option for the project in the `angular.json`.

**Comment by omarbelkhodja-minotore** [comment]
Is HMR supposed to be fully operational now with Angular 19.1.x ? I'm testing using HMR enabled in Storybook. Updating the CSS file is triggering the browser update, but, updating the HTML doesn't, although I do see a message 'hmr update' on the command line.

**Comment by omarbelkhodja-minotore** [comment]
> Is HMR supposed to be fully operational now with Angular 19.1.x ? I'm testing using HMR enabled in Storybook. Updating the CSS file is triggering the browser update, but, updating the HTML doesn't, although I do see a message 'hmr update' on the command line.

OK. I see it is fixed with in the following commit:
https://github.com/analogjs/analog/commit/ee58f28b33aa652b29480eeb887acaa183ed21b5

**Pull request merged**
