### PR TITLE
docs: create and deploy docs website

### LINKED ISSUE #3: [DOCS]: Spin up docs site
Build docs site with:

- Project overview
- Install instructions
- Contributing
- Sponsoring

Options
- Docusaurus
- Hand-rolled
- Other?

It will be hosted on analogjs.org

### PR DESCRIPTION
**Pull request by LayZeeDK**
# References
- Closes #3
- [Preview environment](https://layzeedk.github.io/analogjs-analog/)

# Documentation
- Create docs website using Docusaurus
- Brand Docusaurus theme
- Add logo and favicon
- List features on home page
- Add StackBlitz link to home page
- Add docs pages:
  - *Introduction*
  - *Installation*
  - *Contributors*
  - *Contributing*
    - Describe folder structure
    - Add section on contributing to the docs and website
  - *Sponsoring*

# CI
- Deploy docs website to GitHub Pages

# Build
- Update Node.js to version 16.16.0 to support Docusaurus
- Configure a Yarn workspace to isolate Docusaurus dependencies in the `docs-app` project
- Mark `CONTRIBUTING.md` as implicit dependency for the `docs-app` project to make this Markdown document part of *affected* detection despite it being located outside of the project root
- Add the [`@nx-plus/docusaurus`](https://www.npmjs.com/package/@nx-plus/docusaurus) Nx plugin
- Add `@ngtools/webpack` as an explicit dev dependency to fix the build of the `analog-app` project

# To do
## Before merge
- [x] Filter branches to `main` for `push` events in the CI workflow
- [x] Enable condition for *Upload docs website* step in the `checks` job in the CI workflow
- [x] Enable condition for `deploy-docs` job in the CI workflow
- [x] Configure Docusaurus for upstream organization and repository (`analogjs/analog`)
- [x] Configure Docusaurus for custom domain (`https://analogjs.org`)
- [ ] Select *GitHub Actions* as *Source* in *Settings* -> *Pages* -> *Build and deployment*
- [ ] Configure GitHub Pages for custom domain (`https://analogjs.org`)
- [ ] Configure custom domain DNS records for GitHub Pages

### CODE REVIEW

**Comment by LayZeeDK** [comment]
@brandonroberts 
I'm seeing build errors for the `analog-app` project in this branch:
```
failed to load config from /home/runner/work/analogjs-analog/analogjs-analog/apps/analog-app/vite.config.ts
error during build:
Error: Cannot find module '@ngtools/webpack/src/ivy/transformation'
Require stack:
- /home/runner/work/analogjs-analog/analogjs-analog/node_modules/@analogjs/vite-plugin-angular/src/lib/angular-vite-plugin.js
- /home/runner/work/analogjs-analog/analogjs-analog/node_modules/@analogjs/vite-plugin-angular/src/index.js
- /home/runner/work/analogjs-analog/analogjs-analog/apps/analog-app/vite.config.ts
- /home/runner/work/analogjs-analog/analogjs-analog/node_modules/vite/dist/node/chunks/dep-71eb12cb.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at angular (/home/runner/work/analogjs-analog/analogjs-analog/node_modules/@analogjs/vite-plugin-angular/src/lib/angular-vite-plugin.js:22:54)
    at /home/runner/work/analogjs-analog/analogjs-analog/apps/analog-app/vite.config.ts:50:54
    at loadConfigFromFile (file:///home/runner/work/analogjs-analog/analogjs-analog/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:62783:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolveConfig (file:///home/runner/work/analogjs-analog/analogjs-analog/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:62[39](https://github.com/LayZeeDK/analogjs-analog/runs/7786750995?check_suite_focus=true#step:5:40)8:28)
    at async doBuild (file:///home/runner/work/analogjs-analog/analogjs-analog/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:[43](https://github.com/LayZeeDK/analogjs-analog/runs/7786750995?check_suite_focus=true#step:5:44)3[58](https://github.com/LayZeeDK/analogjs-analog/runs/7786750995?check_suite_focus=true#step:5:59):20)

 >  NX   ERROR: Something went wrong in run-commands - Command failed: vite build

   Pass --verbose to see the stacktrace.
```

I have tried various combinations of regenerating the lockfile without any lock.

**Comment by LayZeeDK** [comment]
Explicitly adding `@ngtools/webpack` as a dev dependency seems to do the trick 💡

**Comment by LayZeeDK** [comment]
Ready for review, @brandonroberts.

**Comment by brandonroberts** [comment]
Awesome work Lars, this is looking great! I'm wondering if the planned features that aren't available yet should be removed from the homepage, such as the file-based routing and SSR/SSG. Or denoted as upcoming.

**Comment by LayZeeDK** [comment]
All right, @brandonroberts. I marked the upcoming features on the home page. You won't be able to see it in the preview environment but here's a screenshot. Other than that, I rebased on top of the latest commit in the `main` branch of this repository.
localhost_3000_ (1)

Feel free to re-approve and merge after taking care of the remaining to-dos which I leave up to you 🙂

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Thanks @LayZeeDK!

**Pull request merged**
