### PR TITLE
feat(create-analog): skip git init flag

### PR DESCRIPTION
**Pull request by miljan-code**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [x] create-analog
- [ ] router
- [ ] platform
- [ ] content
- [ ] nx-plugin
- [ ] trpc

## What is the current behavior?

create-analog always initializes the git repo, even if the project is scaffolded inside the monorepo, where git is already initialized.

## What is the new behavior?

create-analog will initialize a new repo only if cwd and parent directories don't have an initialized git repo. Git init could also be skipped through the --skipGit flag.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by brandonroberts** [comment]
Thanks @miljan-code. What monorepo tool are you using? We have an application generator for Nx already

**Comment by miljan-code** [comment]
> Thanks @miljan-code. What monorepo tool are you using? We have an application generator for Nx already

I'm using turborepo. I did see the Nx support in the documentation, but I have never worked with Nx. I will give it a try, for sure.

**Comment by brandonroberts** [comment]
> > Thanks @miljan-code. What monorepo tool are you using? We have an application generator for Nx already
> 
> I'm using turborepo. I did see the Nx support in the documentation, but I have never worked with Nx. I will give it a try, for sure.

I see. Ok cool, just wondering

**Comment by Micha-Richter** [comment]
Is this pr still in progress?
Had the same problem in a pnpm workspace monorepo recently.

**Comment by Micha-Richter** [comment]
imho this pr here is almost fine: a test case for --skipGit would be good and the function isGitInitialized(dir) is unnecessary, ok. But the failing checks came from main - and are probably corrected in the meantime!?

If it helps I'm also willing to create a new pr for skipping git, @brandonroberts 
Sorry for being annoying ;)

**Comment by brandonroberts** [comment]
> imho this pr here is almost fine: a test case for --skipGit would be good and the function isGitInitialized(dir) is unnecessary, ok. But the failing checks came from main - and are probably corrected in the meantime!?
> 
> If it helps I'm also willing to create a new pr for skipping git, @brandonroberts Sorry for being annoying ;)

I think the `isGitInitialized` could be causing the CI failures. 

Thanks @Micha-Richter, I'll give @miljan-code a little more time to resolve or respond first. There's existing workarounds also

**Comment by brandonroberts** [comment]
@Micha-Richter if you want to open a new PR for this, that would be appreciated. Closing this one for now

**Pull request closed without merging**
