### PR TITLE
feat(router): expose router internals for custom routers

### LINKED ISSUE #904: Enhancing Router Support for Shared Pages in Monorepo Setups
### Which scope/s are relevant/related to the feature request?

router

### Information

I'm working on a monorepo (NX) that includes multiple applications, and I've encountered a challenge with routing for pages shared across these applications. Currently, the router doesn't seem to support monitoring pages outside of the app folder, which is crucial for my setup since the apps are essentially just shells, and all modules and pages are imported from the corresponding folder under the `libs`.

To address this, I wanted to implement a custom router provider.
This required me to access to some internal functions like `createRoutes` and `updateMetaTagsOnRouteChange`, so I exported them in my fork. And it now works on my apps.
( I submitted a merge request to expose those internals: https://github.com/analogjs/analog/pull/903 )

Alternatively, I considered extending `provideFileRouter` with a new `files` parameter, but I think this isn't the right approach since it won't be backwards compatible.

Do you think the custom router provider path is the way to go, or is there another solution?

Thanks a ton for considering my two cents.

### Describe any alternatives/workarounds you're currently using

_No response_

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by n-can-k**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [ ] create-analog
- [X] router
- [ ] platform
- [ ] content
- [ ] nx-plugin
- [ ] trpc

## What is the current behavior?

- The only way to interact with the File-based Router Mechanism is `provideFileRouter` function.
- It only has a set locations to monitor and doesn't have the ability to monitor custom locations for custom routes.

Closes #904 

## What is the new behavior?
Exported internals (createRoutes, Files, and RouteExport) enables developer to provide custom routes

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Thanks! @allcontributors add @n-can-k for code

**Comment by brandonroberts** [comment]
@allcontributors add "@n-can-k" for code

**Comment by nckirik** [comment]
apparently bot has a bug with usernames with multiple hyphens
I wasn't happy with the username anyway, so I changed it to @nckirik

let's try with new username

@allcontributors add @nckirik for code

**Comment by gr2m** [comment]
:wave: maintainer of @all-contributors here, sorry for the noise above, the problem should now be resolved, thanks to @brandonroberts https://github.com/all-contributors/app/pull/463

**Pull request merged**
