### PR TITLE
refactor: update marked to 5.x, node to 18 (LTS)

### PR DESCRIPTION
**Pull request by zawasp**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [x] Other... Please describe: update marked dependency

## Which package are you modifying?

- [ ] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [x] create-analog
- [ ] router
- [ ] platform
- [x] content
- [x] nx-plugin
- [ ] trpc

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by zawasp** [comment]
@brandonroberts should I update engines in packages and apps to node 18? there's one node 14, which is EOL, the rest are 16. Security support for 16 ends in 3 months.

**Comment by brandonroberts** [comment]
@zawasp updating the repo to node 18 is fine. Let's keep support for node 16 in apps a little longer

**Comment by zawasp** [comment]
@brandonroberts fixed conflicts.

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Thanks! @allcontributors add @zawasp for infra

**Pull request merged**
