### PR TITLE
docs(content): add es translations for getting-started and introduction

### PR DESCRIPTION
**Pull request by Villanuevand**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added/updated (for bug fixes/features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [ ] create-analog
- [ ] router
- [ ] platform
- [x] content
- [ ] nx-plugin
- [ ] trpc

## What is the current behavior?

Closes #

## What is the new behavior?

Translate   `getting-started.md` and `introduction.md` to spanish

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## [optional] What [gif](https://chrome.google.com/webstore/detail/gifs-for-github/dkgjnpbipbdaoaadbdhpiokaemhlphep) best describes this PR or how it makes you feel?

Sponge-bob-square-pants-excited

### CODE REVIEW

**Comment by Villanuevand** [comment]
@alejandrocuba this is the first step to start to contribute. 

You just need to copy files in `analog/apps/docs-app
/docs/` to `analog/apps/docs-app
/docs/i18n/es/docusaurus-plugin-content-docs/current`

**Comment by alejandrocuba** [comment]
Thanks for the heads up @Villanuevand! Once this one gets merged, I'll go ahead and create a subsequent PR based on your code changes.

**Comment by Villanuevand** [comment]
@brandonroberts I'm not sure why `build.command` is failing. 
image

**Comment by brandonroberts** [comment]
@Villanuevand the build error should be resolved. Now its failing because of broken links

**Comment by Villanuevand** [comment]
@brandonroberts yeap! 
I'll fix it later today...

**Comment by Villanuevand** [comment]
@brandonroberts Everything looks fine now.

**Comment by alejandrocuba** [comment]
Excellent! @Villanuevand I look forward to forking the main branch after PR gets approved and merged to work on top of your changes.

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
