### PR TITLE
docs: add a docs section for Github Pages Deployment

### LINKED ISSUE #814: Docs: add deployment for Github Pages
### Which scope/s are relevant/related to the feature request?

Docs

### Information

It would be nice to add a docs section for the deployment on Gitlab pages. Of course this has some restrictions but for example it should be possible to deploy a static generated site.

### Describe any alternatives/workarounds you're currently using

_No response_

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by d-koppenhagen**
closes #814

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [ ] create-analog
- [ ] router
- [ ] platform
- [ ] content
- [ ] nx-plugin
- [ ] trpc

## What is the current behavior?

Closes #814

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by brandonroberts — APPROVED** [review]
minor updates

**Comment by d-koppenhagen** [comment]
@brandonroberts can you please review again? I just created an ['Analog Publish Github Pages' Github Action](https://github.com/marketplace/actions/analog-publish-github-pages) and added the information to the docs too.

**Comment by brandonroberts** [comment]
@d-koppenhagen nice!

**Comment by brandonroberts** [comment]
One suggestion for the GitHub Action is to refer to Analog as `AnalogJS` instead of `Analog.js`. Its better for SEO that way

**Comment by d-koppenhagen** [comment]
I will do so!

**Pull request merged**
