### PR TITLE
docs(content): add spanish translation to analogjs.org

### PR DESCRIPTION
**Pull request by Villanuevand**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [ ] create-analog
- [ ] router
- [ ] platform
- [ ] content
- [ ] nx-plugin
- [ ] trpc

## What is the current behavior?

-  

## What is the new behavior?

- Add new `es` locale
- Add full Spanish translation to analogjs website. 
- Add spanish translation to docs sidenav.
- Add commands  `serve-locale` and `write-translations` in `docs-app` project for future translations in other languages.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

#### Overview
image

#### Language Dropdown
image

#### Gets everything ready for Docs translation
image

### CODE REVIEW

**Comment by brandonroberts** [comment]
Thanks @Villanuevand! Do you know what's going on with the docs build failure?

**Comment by Villanuevand** [comment]
@brandonroberts 
There are 2 errors

image


- `docusaurus.config.js(5,15): error TS2339: Property 'plain' does not exist on type 'typeof **import(prism-react-renderer/themes/*)'.` for some reason looks like build breaks [in this line](https://github.com/analogjs/analog/pull/644/files#diff-0a6dfa601739b5de1b51d28765cd9d68432ca11bbf472e8b387390fd85600a3eR5)
The easy way to solve it is to use square bracket notation instead dot notation. 

- `docusaurus.config.js(12,19): error TS2307: Cannot find module '@docusaurus/types' or its corresponding type declarations.` is still under investigation for me. Like usual in our devs lives on my machine works fine. 

image
Even is creating the `es` folder without any problem.

**Comment by brandonroberts** [comment]
Thanks! @allcontributors add @Villanuevand for doc,translation

**Comment by Villanuevand** [comment]
Next step documentation!

**Pull request merged**
