### PR TITLE
feat(vite-plugin-angular): enable `.analog` support

### PR DESCRIPTION
**Pull request by nartc**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [x] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [ ] create-analog
- [ ] router
- [ ] platform
- [ ] content
- [ ] nx-plugin
- [ ] trpc

## What is the new behavior?

This PR enables support for `.analog` file extension via the `supportAnalogFormat` flag under `vite.experimental`.

This replaces the `.ng` file extension support. With `.analog`, the separation is clearer (and intentional). Level of support is around the same as `.ng` with the following difference:

- `templateUrl` is now supported for external HTML file
- `styleUrl` and `styleUrls` are now supported for external style file(s)
- `<style>` (for inline style) is now converted to `styles` property in the Component metadata instead of prepend in the `<template>` content
  - Multiple `<style>` is not guaranteed. If folks need multiple stylesheet, use `styleUrls` instead

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by brandonroberts — APPROVED** [review]
🫡

**Comment by fMoro1999** [comment]
Welcome back 🫶

**Comment by GabrielBB** [comment]
`.anal` would have been better

**Comment by brandonroberts** [comment]
> `.anal` would have been better

**Pull request merged**
