### PR TITLE
fix(vite-plugin-angular): allow build-angular v15

### PR DESCRIPTION
**Pull request by ilteoood**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [X] vite-angular-plugin
- [ ] astro-angular
- [ ] create-analog
- [ ] router

## What is the current behavior?

The peer dependency `@angular-devkit/build-angular` supports only major version 14.

Issue Number: N/A

## What is the new behavior?

The peer dependency `@angular-devkit/build-angular` should also support major version 15.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by brandonroberts — APPROVED** [review]
LGTM

**Comment by brandonroberts** [comment]
Thanks! @allcontributors add @ilteoood for code

**Comment by ilteoood** [comment]
@brandonroberts that was really quick, thanks!
May I ask you for a new release of the plugin?

**Comment by brandonroberts** [comment]
Sure, all packages have been bumped and released

https://github.com/analogjs/analog/commit/a2eab8e7fe5908b95eca37a78553555f3478be3b

**Pull request merged**
