### PR TITLE
docs(content): add turkish translation

### LINKED ISSUE #673: docs: adding turkish language
### Which scope/s are relevant/related to the feature request?

Docs

### Information

I want to contribute to Analog. And I though adding turkish language would be a good start. What do you think @brandonroberts ?

### Describe any alternatives/workarounds you're currently using

N/A

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by besimgurbuz**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [ ] create-analog
- [ ] router
- [ ] platform
- [ ] content
- [ ] nx-plugin
- [ ] trpc

## What is the current behavior?

Closes #673 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by besimgurbuz** [comment]
Hi again @Villanuevand, review would be appreciated!

**Comment by Villanuevand** [comment]
@besimgurbuz everything looks good! 

https://deploy-preview-677--analog-docs.netlify.app/tr/

image

**Comment by Villanuevand** [comment]
@besimgurbuz you just need to update your branch.

**Comment by besimgurbuz** [comment]
I updated the branch and also fixed a translation

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Thanks! @allcontributors add @besimgurbuz for doc,translation

**Pull request merged**
