### PR TITLE
refactor: Node prefix

### LINKED ISSUE #929: Prefix all imports with 'node:'
### Which scope/s are relevant/related to the feature request?

Don't know / other

### Information

Builded files should be able to be executed with deno. (i like to use deno KV in my app)
Most imports are good i think but not all (runtime.mjs):
```
import process from 'node:process';globalThis._importMeta_=globalThis._importMeta_||{url:"file:///_entry.js",env:process.env};import http, { Server as Server$1 } from 'node:http';
import https, { Server } from 'node:https';
import { promises, existsSync } from 'fs'; <----- THIS
import { dirname as dirname$1, resolve as resolve$1, join } from 'path';
import { promises as promises$1 } from 'node:fs';<---- here its correct
import { fileURLToPath } from 'node:url';
```
i assume the one fs import is not compatible with deno given the error message i got:
```
server git:(master) ✗ deno run index.mjs
error: Relative import path "path" not prefixed with / or ./ or ../
If you want to use a built-in Node module, add a "node:" prefix (ex. "node:path").
```

### Describe any alternatives/workarounds you're currently using

_No response_

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by alexfriesen**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [x] vite-plugin-angular
- [x] vite-plugin-nitro
- [ ] astro-angular
- [ ] create-analog
- [ ] router
- [x] platform
- [ ] content
- [x] nx-plugin
- [ ] trpc

## What is the current behavior?

Closes #929 

## What is the new behavior?

"node:" prefixes added to node buildin modules

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by brandonroberts** [comment]
Thanks @alexfriesen. Will you redo this PR against the `beta` branch?

**Comment by alexfriesen** [comment]
@brandonroberts One test case keeps failing. I don't think it's related to my changes as the same test also fails on the beta branch.

Failing Test:
`/packages/vite-plugin-nitro/src/lib/vite-plugin-nitro.spec.ts:292:36`
```
             "output": Object {
       -       "dir": "/custom-root-directory/dist/analog",
       -       "publicDir": "/custom-root-directory/dist/analog/public",
       +       "dir": "/custom-root-directory/some-other-root-directory/analog",
       +       "publicDir": "/custom-root-directory/some-other-root-directory/analog/public",
       +     },
```

**Comment by brandonroberts** [comment]
@alexfriesen you're correct. Its unrelated

**Comment by brandonroberts** [comment]
Thanks! @allcontributors add @alexfriesen for code

**Pull request merged**
