### PR TITLE
docs: add Vercel deploypent provider info

### LINKED ISSUE #493: Docs: add deployment guide for Vercel
### Which scope/s are relevant/related to the feature request?

Docs

### Information

Analog supports deploying to Vercel through a client-only app or SSR app deployed as a Vercel function.

If you want to deploy a fullstack app, you need to adjust the output directory to use Vercel's Build Output API, which is located in the `.vercel` directory at the root of the workspace.

Here's an example repo https://github.com/brandonroberts/analog-angular-vercel-example

We should document deploying to Vercel with minimal configuration

### Describe any alternatives/workarounds you're currently using

_No response_

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by cskiwi**
> remake of #544 because of branching issues on my side

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [ ] create-analog
- [ ] router
- [ ] platform
- [x] content
- [ ] nx-plugin
- [ ] trpc

## What is the current behavior?

Closes #493

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by goetzrobin** [comment]
Did you not have to adjust the Build & Output settings for it to work for you?
My Vercel project uses yarn & nx and I had to manually set my build command.
I just want to confirm 👍  thanks for adding this!

**Review by goetzrobin — CHANGES_REQUESTED** [review]
I do believe we should add a section about the potential changes you need to make on Vercel side if you are using an Nx repo and/or there is no `npm build` command defined in your package.json.

**Comment by cskiwi** [comment]
@goetzrobin good point.

I've created 3 repo's containing the 3 possible combinations.
- Normal create analog project: https://github.com/cskiwi/analog-create
- Nx with support for multipele apps: https://github.com/cskiwi/analog-nx-mono
- Nx standalone app: https://github.com/cskiwi/analog-nx-standalone

It seems that you just have to add the the default project to make the builds work, so this might be something to include into the generator? 

I've update the instructions to include the info on how to do this or define a

**Comment by goetzrobin** [comment]
Looks good to me! @cskiwi unit tests seem to be failing for some reason outside of your scope (since it's only doc changes 🤔) Thank you!

**Review by goetzrobin — APPROVED** [review]

**Pull request merged**
