### PR TITLE
feat(create-analog): skipGit flag to control git initialization

### PR DESCRIPTION
**Pull request by Micha-Richter**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [x] create-analog
- [ ] router
- [ ] platform
- [ ] content
- [ ] nx-plugin
- [ ] trpc

## What is the current behavior?

create-analog always initializes the git repo, even if the project is scaffolded inside a monorepo, where git is already initialized.

## What is the new behavior?

create-analog can be called with --skipGit respectively --no-skipGit to control git initialization. Calling create-analog without one of the two options runs an automatic check for a git repo in cwd and parent directories.

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

Calling create-analog without --skipGit/--no-skipGit in an existing git repo doesn't create a git subrepository anymore.

### CODE REVIEW

**Comment by Micha-Richter** [comment]
How can I correct this stupid mistake? 🙈

**Comment by brandonroberts** [comment]
This commit message has an incorrect scope `test(create-analog-e2e): initialize git; increase max running time for tests`. It should be just `create-analog`. No big deal though, it will get squashed anyway

**Comment by Micha-Richter** [comment]
Yep, I saw it, but had no idea how to fix it. Next time better ;)

Because of the flag: meanwhile i'm unsure whether skipGit better should be working like skipTailwind? Ask the user and let her make a decision.. 🤷‍♂️

**Comment by brandonroberts** [comment]
> Yep, I saw it, but had no idea how to fix it. Next time better ;)
> 
> Because of the flag: meanwhile i'm unsure whether skipGit better should be working like skipTailwind? Ask the user and let her make a decision.. 🤷‍♂️

Yea, I think giving them the prompt would be more flexible than trying to auto-detect, with a default to yes/true

**Comment by Micha-Richter** [comment]
Will change it.

**Pull request closed without merging**
