### PR TITLE
feat(nx-plugin): TRPC using base url depending on the provider

### PR DESCRIPTION
**Pull request by cskiwi**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [ ] create-analog
- [ ] router
- [ ] platform
- [ ] content
- [x] nx-plugin
- [ ] trpc

## What is the current behavior?

In the current implementation, the app defaults to running trpc on http://127.0.0.1:4200/. To enhance flexibility and accommodate different hosting providers, this pull request introduces a getBaseUrl function. With this update, the trpc endpoint can be easily adjusted based on the hosting environment. Changing the port or any other configurations will now be automatically resolved, providing a more adaptable and seamless experience.

This change aims to improve the app's configurability and ensure smoother deployments across various hosting setups. Your review and feedback on this pull request would be highly appreciated. Thank you!

Closes #

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by goetzrobin** [comment]
I really like this! 
In an ideal world the user does not have to worry about setting an absolute path at all and can simply put "/api/trpc", "trpc", etc.

Maybe this should be exposed as a function of the trpc package instead of the Nx plugin template?
@brandonroberts @cskiwi what do you guys think?

**Comment by cskiwi** [comment]
> I really like this! In an ideal world the user does not have to worry about setting an absolute path at all and can simply put "/api/trpc", "trpc", etc.
> 
> Maybe this should be exposed as a function of the trpc package instead of the Nx plugin template? @brandonroberts @cskiwi what do you guys think?

@goetzrobin That sounds like a good idea. However, before implementing it into the 'trpc' package, we should take a look at resolving the following issue: https://github.com/analogjs/analog/issues/468. 

This precautionary step is necessary to ensure that we don't introduce any breaking changes, especially if addressing the issue requires making additional changes to the way the API is passed along. By doing this, we can assist the users while still retaining the flexibility to make changes to the 'trpc' package in the future.

**Comment by goetzrobin** [comment]
Hey there @cskiwi! Check out this PR: https://github.com/analogjs/analog/pull/639 
There might still be some gotchas I am missing, but it seems like it would make a `getBaseUrl` unnecessary and the TrpcClient would "just" work!

**Comment by cskiwi** [comment]
> Hey there @cskiwi! Check out this PR: #639 There might still be some gotchas I am missing, but it seems like it would make a `getBaseUrl` unnecessary and the TrpcClient would "just" work!

Oh nice! this would be beautifull for the developer experience!

**Comment by brandonroberts** [comment]
Closing as resolved via #639 which will go out with the next release

**Pull request closed without merging**
