### PR TITLE
feat: change output directory from "server" to "analog"

### LINKED ISSUE #295: Feature: change output directory for server build to "analog" instead of "server"
### Which scope/s are relevant/related to the feature request?

platform

### Information

When a server build is produced, a few directories are created

- dist
  - .nitro  
  - client (Client build)
  - server <-- changed to analog
    - public
    - server
  - ssr (SSR build)

### Describe any alternatives/workarounds you're currently using

_No response_

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by goetzrobin**
made the changes so the vite-nitro-plugin.ts outputs to an "analog" folder instead of "server" folder. added an integration test for the blog-app that uses the build output from said "analog" folder. Tried to do the same for the analog-app but ran
 into this issue with nx and cypress: https://github.com/nrwl/nx/issues/10814.
 Waiting for guidance on that before making any other e2e changes.
 I think ideally we check this output as part of the e2e test
 for create analog as described in issue #201.

Closes #295

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [x] vite-angular-plugin
- [ ] astro-angular
- [ ] create-analog
- [ ] router
- [ ] platform
- [ ] content

## What is the current behavior?
Final output that makes up the Analog server is in the server directory

Issue Number: #295 

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

Deploy scripts of applications using default paths need to be updated to point to the analog directory instead of server directory

### CODE REVIEW

**Comment by goetzrobin** [comment]
@brandonroberts netlify deploy is most likely failing due to the fact that the output directory was renamed. I didn't see a way to make changes to the netlify config in the repo. I assume it is some change in Github? 
Let me know if there's anything I can do to address this or if you will take care of it!

Thank you!

**Comment by brandonroberts** [comment]
Thank @goetzrobin! I updated the Netlify config to the new directory and restarted the deploy previews

**Comment by brandonroberts** [comment]
@goetzrobin docs need updating also

https://github.com/analogjs/analog/blob/main/apps/docs-app/docs/features/deployment/overview.md

**Comment by goetzrobin** [comment]
> Blog app should be resolved also https://deploy-preview-300--analog-blog.netlify.app/blog

I got a 404 for that url, but that url only. Everything else works and https://deploy-preview-300--analog-blog.netlify.app also redirects correctly. I added /blog to the pre-rendered routes.

All looks good to me now 🚀

**Pull request merged**
