### PR TITLE
docs: add reference to Qwik City in the introduction page

### PR DESCRIPTION
**Pull request by ciradu2204**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [ ] create-analog
- [ ] router
- [ ] platform
- [ ] content
- [ ] nx-plugin
- [ ] trpc

## What is the current behavior?

Issue Number: #418 

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by brandonroberts — APPROVED** [review]

**Comment by ciradu2204** [comment]
@brandonroberts, when I checked the URL referenced on the doc, there was no city in the name. 
Screen Shot 2023-05-23 at 19 21 09

**Comment by brandonroberts** [comment]
@ciradu2204 its on there docs page https://qwik.builder.io/docs/qwikcity/

**Comment by ciradu2204** [comment]
okay, great. Thanks

**Comment by brandonroberts** [comment]
Thanks! @allcontributors add @ciradu2204 for doc

**Pull request merged**
