### PR TITLE
feat(create-analog): adding an option to select the ui framework

### PR DESCRIPTION
**Pull request by cskiwi**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [x] create-analog
- [ ] router
- [ ] platform
- [ ] content
- [ ] nx-plugin
- [ ] trpc

## What is the current behavior?
the option `--skipTailwind` has been changed with an `--ui` option that allows the selection of the UI framework the developer wants to use

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

existing commands using the `--skipTailwind` won't work anymore

### CODE REVIEW

**Comment by brandonroberts** [comment]
Thanks @cskiwi. I need to think about this more. Not certain we should go down this route though with so many options out there. Today, it's Material and Tailwind. Tomorrow it's Material, Tailwind, Taiga UI, Bootstrap, Clarity, etc. We want to keep `create-analog` minimal and leave it up to the developer to tailor it further. I also don't see Tailwind/Material as mutually exclusive.

I could see the CLI go in the direction of picking what type of app you'd like to build. 

- Blog
- Todos (Fullstack Example)
- Barebones

We also have #517 which would change the work being done here also.

**Comment by cskiwi** [comment]
@brandonroberts Sounds like a good direction to navigate to.

I've added the material stuff mostly because that's mostly what I've been using for the last 8-ish years. So creating new projects directly with Material included would save me some time.

Of course if it was fully integrated it with nx, then we would only have to validate that the normal way of adding angular material to a nx app works, and we'd be golden

**Comment by goetzrobin** [comment]
@brandonroberts seems like what you are describing is along the lines of this effort, too: 
https://github.com/analogjs/analog/issues/413

Are you suggesting we'd continue to ask for tailwind like we currently do and then ask for the type of application?

**Comment by brandonroberts** [comment]
@goetzrobin yes, I think the type of app you want to build and using Tailwind are two separate questions. Asking what type of app will generate a starter app from a template we have.

**Comment by goetzrobin** [comment]
Awesome! I like that approach a lot!

**Pull request closed without merging**
